services:
  - type: web
    name: energy-mix-backend
    runtime: docker
    rootDir: backend
    dockerfilePath: ./Dockerfile
    healthCheckPath: /

  - type: web
    name: energy-mix-frontend
    runtime: docker
    rootDir: frontend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: BACKEND_URL
        sync: false
